### ISSUE TITLE
KMI meteo data WFS service

### ISSUE THREAD

**Issue by hansvancalster** [inbo/inbospatial#5]
See this service https://opendata.meteo.be/service/wfs?REQUEST=GetCapabilities&SERVICE=WFS
and https://opendata.meteo.be/geonetwork/srv/eng/catalog.search#/metadata/RMI_DATASET_SYNOP

show how to get the synoptic data (in a vignette or contribute to INBO tutorial about WFS?).

**Comment by florisvdh** [comment]
INBO tutorial: I propose to at least add the URLs to the list of available WFS/WCS. If there is no example with WCS yet, maybe that's an idea to add another example.

The tutorial makes no use of **inbospatial**; I think the coding approach there is OK to keep as-is but a supplementary package vignette using **inbospatial** functions could be an interesting match.

**Comment by hansvancalster** [comment]
There is now an example of this in the vignette of the package and the URL is also added to the inbo/tutorial about WFS services
